### ISSUE TITLE
Problem with sessions

### ISSUE THREAD

**Issue by webspec2012** [Baldinof/roadrunner-bundle#114]
Good afternoon! Faced a problem with using sessions.

I use Symfony 6.2.

Sometimes it works fine, and sometimes the session is recreated every time. The problem does not reproduce if the application is running in DEV mode. And also if you run it in PROD mode, but set `http.pool.num_workers = 1'.

Changing `kernel_reboot.strategy` to `always` does not lead to anything.

**Comment by Baldinof** [comment]
Hello, 

I tried on a fresh project, and it seems to be working with default configuration.

What version of this package and Symfony are you using?

Can you share your session config in `config/packages/framework.yaml`?

**Comment by webspec2012** [comment]
Good afternoon!

Im use:

* symfony/security-bundle 6.2.10
* baldinof/roadrunner-bundle 3.0.0

Config:

```
    session:
        name: 'rtsid'
        handler_id: app.sessions.handler
        cookie_secure: auto
        cookie_samesite: lax
```

Services

```
    app.sessions.cache:
        class: \Symfony\Component\Cache\Adapter\RedisTagAwareAdapter
        arguments:
            $redis: '@app.sessions.redis'

    app.sessions.handler:
        class: App\FrontendWeb\Security\WebSession\WebSessionRedisHandler
        arguments:
            $webSessionCache: '@app.sessions.cache'
```
