### ISSUE TITLE
The RoadRunner plugin 'rpc' is disabled, try to add a `rpc` section to the configuration file.

### ISSUE THREAD

**Issue by FluffyDiscord** [Baldinof/roadrunner-bundle#121]
The RR output tells me that the RPC plugin has indeed started, any ideas? Also this is weird, since my other project adds centrifuge worker that RR can proxy with and that works just fine, even thought it also requires RPC

```yaml
version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

service:
  crontab:
    command: "crond -f"
    process_num: 1
    exec_timeout: 0s
    remain_after_exit: true
    service_name_in_log: true
    restart_sec: 1

kv:
  memory:
    driver: memory
    config: { }

rpc:
  listen: tcp://127.0.0.1:6002

http:
  address: 0.0.0.0:8080
  workers:
    debug: 1
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

logs:
  mode: development
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: debug
```

![image](https://github.com/Baldinof/roadrunner-bundle/assets/10332247/b245c5b9-fc04-4a03-91c1-6cfadc47812a)

baldinof/roadrunner-bundle 3.0.0
spiral/roadrunner-kv 4.0.0
spiral/roadrunner-cli 2.5.0
