### ISSUE TITLE
phpfpm faster than roadrunner

### ISSUE THREAD

**Issue by mpoiriert** [Baldinof/roadrunner-bundle#143]
I am trying roadrunner for the first time. 

I am using it via my docker local setup.

I have both phpfpm and roadrunner running.

When refreshing a page vai phpfpm the reponse time is about 35-40 ms (using profiler of symony)
In roadrunner I sometime get 19ms (which is great) but sometime 115ms. the average is higher than the one from phpfpm

I have "hack" symfony to have profiler but the config cache debug is set to false. That way I can mimic what will happen in prod but still have the profiler.

Symfony initialization take about 5 ms for phpfpm and 1ms (constantly) for RR. But all the other code are pretty constant for phpfm but are not for rr:

PHP FPM

![image](https://github.com/Baldinof/roadrunner-bundle/assets/4175616/760daaee-6a0b-4686-a5da-b2448012d015)

Road Runner

![image](https://github.com/Baldinof/roadrunner-bundle/assets/4175616/c7d2edcf-c258-483b-9bfe-2b0735bd14d8)

This is a small project sandbox so the gain for the symfony initialization is not great. for bigger project I am assuming symfony initiliazation will see better gain but I am not sure it will overcome the setting.

Also note that I am using rr serve and not rr server -c .rr.dev.yaml

Using rr with dev goes to 180 ms per request, I am assuming the "file change check" is way slower that what symfony does.

Apcu is enable for cli, so this is not the issue.

No query to doctrine for this specicific page

**Comment by rmikalkenas** [comment]
@mpoiriert you should write the issue directly to roadrunner: https://github.com/orgs/roadrunner-server/discussions
it's not related to this bundle

**Comment by mpoiriert** [comment]
I thought that maybe  some things are specific to Symfony that's why I
asked here.

**Comment by Kaspiman** [comment]
@mpoiriert Hello, please show your `rr.yaml` config

**Comment by mpoiriert** [comment]
Here is the file:

```YAML
version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  pool:
    debug: false
    num_workers: 8      # Adjust based on your system's CPU cores
    max_jobs: 4000        # Maximum number of jobs a worker can handle before being recycled
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

logs:
  mode: production
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: error

# Uncomment to use metrics integration
# rpc:
#   listen: tcp://127.0.0.1:6001

# Uncomment to use metrics integration
# metrics:
#   # prometheus client address (path /metrics added automatically)
#   address: "0.0.0.0:9180"

```
