### ISSUE TITLE
Worker not creating unix socket

### ISSUE THREAD

**Issue by TimJones** [Baldinof/roadrunner-bundle#20]
I have the bundle installed in a Symfony 5 based app and the command is showing up in the console as expected
```shell
$ php apps/rrtest/bin/console.php list
Symfony 5.1.5 (env: local, debug: true)

...snip...
 baldinof
  baldinof:roadrunner:worker    Run the roadrunner worker
...snip...
```
but running RoadRunner fails because the socket has not been created.
```shell
$ rr serve -d -v -c .rr.yaml
WARNING: Native build is an experimental feature and could change at any time
Creating busuu-dev_courses-service_run ... done
DEBU[0000] [metrics]: disabled
DEBU[0000] [headers]: disabled
DEBU[0000] [static]: disabled
DEBU[0000] [health]: disabled
DEBU[0000] [reload]: disabled
DEBU[0000] [rpc]: disabled
DEBU[0000] [http]: started
ERRO[0000] [http]: [http]: listen unix var/roadrunner.sock: bind: no such file or directory
DEBU[0000] [rpc]: stopped
Error: [http]: listen unix var/roadrunner.sock: bind: no such file or directory
```
My `.rr.yaml` is very basic
```yaml
rpc:
  enabled: false
http:
  address: "0.0.0.0:8080"
  workers:
    command: php/apps/rrtest/bin/console.php baldinof:roadrunner:worker
    relay: unix://var/roadrunner.sock
```

**Comment by Baldinof** [comment]
Hi, it looks like you are not running roadrunner from the project directory. If so, you should change the socket path, like you did for `bin/console`:

```yaml
# .rr.yaml
http:
  address: "0.0.0.0:8080"
  workers:
    command: php/apps/rrtest/bin/console.php baldinof:roadrunner:worker
    relay: unix://php/apps/rrtest/var/roadrunner.sock
```
If you want, you can redefine `Spiral\Goridge\RelayInterface` to use a custom path for the socket:

```yaml
# config/services.yaml
services:
  Spiral\Goridge\RelayInterface:
    class: 'Spiral\Goridge\SocketRelay'
    arguments:
      - '/your/custom/path'
      - null
      - 1 # SocketRelay::SOCK_UNIX
```

You can also use a TCP socket, see https://github.com/Baldinof/roadrunner-bundle#configuration
