### ISSUE TITLE
Proposal: Introduce kernel_reboot.strategy: never configuration

### ISSUE THREAD

**Issue by fitzel** [Baldinof/roadrunner-bundle#24]
First of all thanks a lot for this great package. Together with roadrunner it has given us insane possibilities to improve performance! :)

Mainly we are getting this performance boost by loading lots of data to runtime on this event:
`Baldinof\RoadRunnerBundle\Event\WorkerStartEvent`

With the introduction of v1.3 the kernel gets rebooted on exceptions (which caused a lot of WTFs on ours side because this is new behaviour 🤪 ) 

It would be great to have a configuration method where this behaviour can be turned off. As it was until v1.3. E.g. `KERNEL_REBOOT_STRATEGY_NEVER`

Right now we have an implicit "workaround" by configuring the bundle like so:
```yml
baldinof_road_runner:
    kernel_reboot:
        strategy: on_exception
        allowed_exceptions:
            - Throwable
```

The following would be a bit more readable
```yml
baldinof_road_runner:
    kernel_reboot:
        strategy: never
```

Thanks for considering and thanks a lot for all the work put into this project!
