### ISSUE TITLE
Make bundle compatible with RoadRunner v2

### ISSUE THREAD

**Issue by bheisig** [Baldinof/roadrunner-bundle#29]
Yesterday [Spiral released version 2.0.0 of RoadRunner](https://github.com/spiral/roadrunner/releases/tag/v2.0.0). It has a bunch of interesting new features and improvements but also introduces some breaking changes.

Do you have any plans to make your bundle compatible with RR v2?

**Comment by Baldinof** [comment]
Hi, nice :) I missed the released.

I might work on it this weekend, but I cannot give you an release date.

I would obviously accept a PR if someone want to accelerate on this.

**Comment by bheisig** [comment]
Hi, thanks for the fast feedback! No pressure. Sounds good to me. Since it's a major release I'll wait for the obvious bug fix releases in the near future ;-) Until then I'd like to test & stress v2 as soon as possible.

**Comment by Baldinof** [comment]
I could not resist and I played a little with it, performances seems crazy :) We are talking in microseconds on a dummy controller.

```2021-03-03T19:41:37.819+0100	DEBUG	http	http/plugin.go:112	200 GET http://localhost:8080/ping	{"remote": "127.0.0.1", "elapsed": "522.98µs"}```

A simple load test with bombardier give 10k req/s with 4 workers (i7 macbook pro): 

```❯ bombardier localhost:8080/ping
Bombarding http://localhost:8080/ping for 10s using 125 connection(s)
[====================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     10288.62     960.94   12302.74
  Latency       12.15ms     1.21ms    29.40ms
  HTTP codes:
    1xx - 0, 2xx - 102998, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:     2.92MB/s
```

Everything seems working, but I need to double check integrations. I might release a v2 next week :)

Awesome work @48d90782 and @wolfy-j!

**Comment by wolfy-j** [comment]
I can guarantee you that you can gain an extra 5-20% by connecting RR to HttpKernel directly, without a PSR-7 bridget. We do provide HttpWorker abstraction.

**Comment by Baldinof** [comment]
👍  I will try without PSR-7, but integrations are written as PSR-15 middlewares, it would require a big rewrite of them.

**Comment by wolfy-j** [comment]
Then it's easier to leave PSR-7 just for easier maintaince.

**Comment by hugochinchilla** [comment]
Is someone already working on it? if not I can start working on a PR

**Comment by Baldinof** [comment]
Thanks but I'm working on it here https://github.com/Baldinof/roadrunner-bundle/issues/29

I have something good locally, but I still need to update the documentation / flex recipe. I will try to accelerate on this :)

**Comment by Baldinof** [comment]
I need some feedbacks here, I tried to remove the PSR7 layer and the gain is around 15% (as per @wolfy-j prediction).

The question is: do you use custom psr15 middlewares or are you just using the bundle provided integrations?

@hugochinchilla @bheisig

**Comment by bheisig** [comment]
@Baldinof We're only using the bundle-provided middlewares

**Comment by hugochinchilla** [comment]
Same here

**Comment by treadmillian** [comment]
Same here

**Comment by ad3n** [comment]
same here

**Comment by Baldinof** [comment]
I think #31 is ready now :)

I will work on the flex part and release a beta soon.

If someone wants to do a review on the PR, it's the time :)

**Comment by surya4crowde** [comment]
hi @Baldinof i will test

**Comment by surya4crowde** [comment]
i got this error `Error: [http]: unable to connect to worker: worker is gone: exit status 1`

**Comment by Baldinof** [comment]
Hi, thank you for giving it a try.

I think you need to update you `rr` binary, can you try to run `vendor/bin/rr get-binary --location bin`?

I added this missing step to the upgrade guide.

**Comment by surya4crowde** [comment]
@Baldinof : Thank you for your suggestion, now the server is running buat the web can not access

```yaml
http:
    address: "0.0.0.0:8080"
    uploads:
        forbid: [".php", ".exe", ".bat"]
    workers:
        command: "/usr/bin/php /semart/bin/console baldinof:roadrunner:worker"
        relay: "unix://var/roadrunner.sock"
static:
    dir:   "public"
    forbid: [".php", ".htaccess"]

```

I check, `roadrunner.sock` is not exist

**Comment by hugochinchilla** [comment]
I will try to test this today and give feedback by the end of the day

**Comment by bricelalu** [comment]
> @Baldinof : Thank you for your suggestion, now the server is running buat the web can not access
> 
> ```yaml
> http:
>     address: "0.0.0.0:8080"
>     uploads:
>         forbid: [".php", ".exe", ".bat"]
>     workers:
>         command: "/usr/bin/php /semart/bin/console baldinof:roadrunner:worker"
>         relay: "unix://var/roadrunner.sock"
> static:
>     dir:   "public"
>     forbid: [".php", ".htaccess"]
> ```
> 
> I check, `roadrunner.sock` is not exist

Hi @surya4crowde , with roadrunner V2, the yaml config file has a different format now: https://roadrunner.dev/docs/intro-config, this link could help

**Comment by fwolfsjaeger** [comment]
@surya4crowde That config is for v1, you'll have to move http.address to server.command.

```yaml
server:
  command: "php bin/console baldinof:roadrunner:worker"

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
```

**Comment by Baldinof** [comment]
You can run `cp vendor/baldinof/roadrunner-bundle/.rr.* .` to copy the new default configuration files

See https://github.com/Baldinof/roadrunner-bundle/blob/2.x/UPGRADE-2-0.md

**Comment by hugochinchilla** [comment]
@Baldinof I can confirm this is working fine for me.

**Comment by Baldinof** [comment]
Thanks @hugochinchilla

I just tagged 2.0.0 and made `2.x` the new default branch :)

The upgrade documentation is [here](https://github.com/Baldinof/roadrunner-bundle/blob/2.x/UPGRADE-2-0.md) and the README is up to date. 

The [flex recipe PR](https://github.com/symfony/recipes-contrib/pull/1116) is still waiting for a merge.

On a fresh symfony installation it's performing at **9100 req/s vs 6400** for the v1 branch on my computer.

I will keep the issue opened for some days to handle feedbacks here if there is any.

**Comment by rustatian** [comment]
@Baldinof Thanks for the great integration. One little note, since `v2.0.4` the worker `stderr` is handled as `INFO` log level, so, it's not necessary to see all debug logs (https://github.com/Baldinof/roadrunner-bundle/issues/29#issuecomment-814351450) from the server plugin now 😄 
Also, there is a new `raw` mode, in which PHP worker stderr comes to the RR stderr totally unmodified. If you pushed, let's say, `{"Baldinof": "cool"}` you'll see that in the RR stderr w/o any modifications (like `10:00 DEBUG plugin.go:33 {"Baldinof": "cool"}`).

**Comment by Baldinof** [comment]
This is very cool! I updated the default configurations with these changes

**Comment by treadmillian** [comment]
UPDATE 1:  Is this related to https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/620?  Though I'm currently using Symfony 5.2.6

UPDATE 2: requiring `composer require nyholm/psr7` seems to have resolved this issue, even though the above linked issue said it wouldn't.

Hi @Baldinof 

I'm getting this error.  Have followed the instructions on your updated README and updated the .rr.* config files.

```
http_plugin_serve_http: SoftJobError:
	error encoder:
	sync_worker_exec_payload: Error: Class 'Nyholm\Psr7\Factory\Psr17Factory' not found in /app/cache/Container72rxwpz/getDebug_SensioFrameworkExtra_Psr7_ArgumentValueResolver_ServerRequestService.php:26
Stack trace:
#0 /app/cache/Container72rxwpz/App_KernelDevDebugContainer.php(560): Container72rxwpz\getDebug_SensioFrameworkExtra_Psr7_ArgumentValueResolver_ServerRequestService::do()
#1 /app/cache/Container72rxwpz/App_KernelDevDebugContainer.php(1272): Container72rxwpz\App_KernelDevDebugContainer->load()
#2 /app/vendor/symfony/http-kernel/Controller/ArgumentResolver.php(51): Container72rxwpz\App_KernelDevDebugContainer->Container72rxwpz\{closure}()
#3 /app/vendor/symfony/http-kernel/Controller/TraceableArgumentResolver.php(38): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments()
#4 /app/vendor/symfony/http-kernel/HttpKernel.php(149): Symfony\Component\HttpKernel\Controller\TraceableArgumentResolver->getArguments()
#5 /app/vendor/symfony/http-kernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#6 /app/vendor/symfony/http-kernel/Kernel.php(195): Symfony\Component\HttpKernel\HttpKernel->handle()
#7 /app/vendor/baldinof/roadrunner-bundle/src/Http/KernelHandler.php(45): Symfony\Component\HttpKernel\Kernel->handle()
#8 [internal function]: Baldinof\RoadRunnerBundle\Http\KernelHandler->handle()
#9 /app/vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php(94): Generator->current()
#10 /app/vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php(72): Baldinof\RoadRunnerBundle\Http\Runner->getResponse()
#11 /app/vendor/baldinof/roadrunner-bundle/src/Integration/PHP/NativeSessionMiddleware.php(34): Baldinof\RoadRunnerBundle\Http\Runner->handle()
#12 [internal function]: Baldinof\RoadRunnerBundle\Integration\PHP\NativeSessionMiddleware->process()
#13 /app/vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php(94): Generator->current()
#14 /app/vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php(80): Baldinof\RoadRunnerBundle\Http\Runner->getResponse()
#15 /app/vendor/baldinof/roadrunner-bundle/src/Integration/Doctrine/DoctrineORMMiddleware.php(59): Baldinof\RoadRunnerBundle\Http\Runner->handle()
#16 [internal function]: Baldinof\RoadRunnerBundle\Integration\Doctrine\DoctrineORMMiddleware->process()
#17 /app/vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php(94): Generator->current()
#18 /app/vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php(80): Baldinof\RoadRunnerBundle\Http\Runner->getResponse()
#19 /app/vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php(34): Baldinof\RoadRunnerBundle\Http\Runner->handle()
#20 [internal function]: Baldinof\RoadRunnerBundle\Http\MiddlewareStack->handle()
#21 /app/vendor/baldinof/roadrunner-bundle/src/Worker/Worker.php(61): Generator->current()
#22 /app/vendor/baldinof/roadrunner-bundle/src/Command/WorkerCommand.php(68): Baldinof\RoadRunnerBundle\Worker\Worker->start()
#23 /app/vendor/symfony/console/Command/Command.php(256): Baldinof\RoadRunnerBundle\Command\WorkerCommand->execute()
#24 /app/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run()
#25 /app/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand()
#26 /app/vendor/symfony/console/Application.php(290): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#27 /app/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun()
#28 /app/vendor/symfony/console/Application.php(166): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#29 /app/bin/console(43): Symfony\Component\Console\Application->run()
#30 {main}
```

app/config/packages/baldinof_road_runner.yaml
```yaml
baldinof_road_runner:
    # The kernel is preserved between requests. Change this to `always`
    # if you want to reboot it, and use a fresh container on each request.
    kernel_reboot:
        strategy: on_exception
        allowed_exceptions:
            - Symfony\Component\HttpKernel\Exception\HttpExceptionInterface
            - Symfony\Component\Serializer\Exception\ExceptionInterface

    # Integrations are automatically detected, depending on installed bundle & current configuration
    # See https://github.com/baldinof/roadrunner-bundle#integrations
    default_integrations: true

    # Allow to send prometheus metrics to the master RoadRunner process,
    # via a `Spiral\RoadRunner\MetricsInterface` service.
    # See https://github.com/baldinof/roadrunner-bundle#metrics
    metrics:
        enabled: false
        collect:
            user_login:
                type: counter
                help: "Number of logged in user"

    # You can use middlewares to manipulate PSR requests & responses.
    # See https://github.com/baldinof/roadrunner-bundle#middlewares
    # middlewares:
    #     - App\Middleware\YourMiddleware
```

.rr.dev.yaml
```yaml
server:
   command: "php bin/console baldinof:roadrunner:worker"

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

logs:
  mode: development
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: debug # Everything written to worker stderr is logged
    metrics:
      level: debug

reload:
  enabled: true
  interval: 1s
  patterns: [".php", ".yaml"]
  services:
    http:
      dirs: ["."]
      recursive: true
```
