### ISSUE TITLE
No logs on stdout/err

### ISSUE THREAD

**Issue by TimJones** [Baldinof/roadrunner-bundle#32]
Hi, i have to support a non-standard Symfony application and they can't seem to get logs to stdout or stderr.

It's using RoadRunner v1.8.4 in a docker container with a unix socket. I think it's using Monolog v2.0, but nothing logged is being directed to stdout or stderr.

The `rr.yaml` is:

```yaml
rpc:
  enable: false
http:
  address: "0.0.0.0:8080"

  workers:
    command: php apps/courses/bin/console.php baldinof:roadrunner:worker
    relay: unix:///opt/app/roadrunner.sock
```
