### ISSUE TITLE
After few days it does not recreate workers

### ISSUE THREAD

**Issue by make-it-git** [Baldinof/roadrunner-bundle#50]
> bin/rr -c .rr.yaml http:workers      
+---------+-----------+---------+---------+--------------------+
|   PID   |  STATUS   |  EXECS  | MEMORY  |      CREATED       |
+---------+-----------+---------+---------+--------------------+
+---------+-----------+---------+---------+--------------------+

Supervisord config

> [program:roadrunner]
command=/usr/bin/env NUM_WORKERS=30 RPC_ADDRESS=tcp://127.0.0.1:9080 LISTEN_ADDRESS=127.0.0.1:8080 /var/www/application/bin/rr serve -c .rr.yaml
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
loglevel=debug
startsecs=4
startretries=999999
user=www-data
redirect_stderr=true
directory=/var/www/application/
stopwaitsecs=4

If i kill the process which states `bin/rr -c .rr.yaml serve` supervisord correctly restarts `serve` process which in turn recreates all http workers.

My environment

> RoadRunner, PHP Application Server
Version: 1.9.2, 2021-01-14T18:50:40+0000

> $ php --version
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

composer.json excerpt
> "baldinof/roadrunner-bundle": "^1.5"
"symfony/framework-bundle": "4.4.*",

.rr.yaml
```
rpc:
  enable: true
  listen: ${RPC_ADDRESS}
http:
  address: ${LISTEN_ADDRESS}
  appErrorCode: 500
  internalErrorCode: 500
  http2:
    enabled: true
    h2c: true
    maxConcurrentStreams: 128
  maxRequestSize: 16
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  trustedSubnets: [ "10.0.0.0/8", "127.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7", "fe80::/10" ]
  workers:
    command: "php bin/console baldinof:roadrunner:worker"
    relay: "unix://var/roadrunner.sock"
    pool:
      numWorkers: ${NUM_WORKERS}
      maxJobs: 500
      allocateTimeout: 60
      destroyTimeout: 60

static:
  dir:   "public"
  forbid: [".php", ".htaccess"]

limit:
  interval: 1
  services:
    http:
      maxMemory: 64
      TTL: 600
      idleTTL: 60
      execTTL: 60
```

How can i debug why `serve` does not recreate workers? It works after full restart (killing `serve` process which is recreated by supervisord) for a few days and after that I have to restart it to work as expected.
