### ISSUE TITLE
kernel_reboot: strategy: always does not work

### ISSUE THREAD

**Issue by jzyinq** [Baldinof/roadrunner-bundle#51]
Hi,

Having such configuration in `baldinof_road_runner.yaml` (2.1.0)

```yaml
baldinof_road_runner:
    kernel_reboot:
        strategy: always

    # Integrations are automatically detected, depending on installed bundle & current configuration
    # See https://github.com/baldinof/roadrunner-bundle#integrations
    default_integrations: true

    # Allow to send prometheus metrics to the master RoadRunner process,
    # via a `Spiral\RoadRunner\MetricsInterface` service.
    # See https://github.com/baldinof/roadrunner-bundle#metrics
    metrics:
        enabled: false
```

I'm encountering situations where response seems to be mixed with previous responses - how can I confirm that kernel is rebooting and I have a problem somewhere else?
