### ISSUE TITLE
Running RoadRunner in ECS behind an ALB

### ISSUE THREAD

**Issue by digitalkaoz** [Baldinof/roadrunner-bundle#69]
Hey,

startup works fine, but i see the app somehow assumes the current domain is the internal ECS Container IP. How can we fix this?

So basically its a `FORWARDED` issue i guess.

My config:

```yaml
version: "2.7"

server:
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

  command: "php bin/console baldinof:roadrunner:worker"

http:
  address: "0.0.0.0:8000"
  middleware: [ "static", "gzip" ]
  #pool:
  #  num_workers: 8
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

logs:
  level: warn
```

it works fine locally but not behind an LB

in our Symfony Front Controller we had to do this

```php
$trustedProxies = $_ENV['TRUSTED_PROXIES'];
if ($trustedProxies) {
    Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_FOR | Request::HEADER_X_FORWARDED_PORT | Request::HEADER_X_FORWARDED_PROTO | Request::HEADER_FORWARDED | Request::HEADER_X_FORWARDED_AWS_ELB);
}
```

using `public/index.php` somehow didnt work (the `symfony/runtime` is installed)

**Comment by Baldinof** [comment]
Hi!

What version of Symfony / RR / this bundle are you using?

I think the code you modified here https://github.com/Baldinof/roadrunner-bundle/pull/70 might not be needed anymore as Symfony handle that with config now (https://symfony.com/doc/current/deployment/proxies.html#solution-settrustedproxies).

I will try to have a closer look tomorow

**Comment by digitalkaoz** [comment]
I think its not about about trusted proxies, its about parsing the FORWARD
header. Symfony5.4 & Roadrunner 2.8

Baldinof ***@***.***> schrieb am Do., 17. Feb. 2022, 22:35:

**Comment by Baldinof** [comment]
There is a `trusted_headers` config option to trust the `Forwarded` header.

Also I think if you are behind a AWL LB you need to use `REMOTE_ADDR` in `trusted_proxies` see: https://symfony.com/doc/current/deployment/proxies.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly

The problem is Symfony will resolve the REMOTE_ADDR on worker boot, but the value might change during a worker life as the request might came from another LB.

I faced this issued on Google Cloud Run and used a middleware like this:

```php
class TrustedProxiesMiddleware implements MiddlewareInterface
{
    public function __construct(private string $trustedProxies, private int $trustedHeaderSet)
   {}

    public function process(Request $request, HttpKernelInterface $next): \Iterator
    {
        if (str_contains($this->trustedProxies, 'REMOTE_ADDR')) {
            $proxies = [];
            foreach(explode(',', $this->trustedProxies) as $proxy) {
                $proxy = trim($proxy);
                if ($proxy === 'REMOTE_ADDR') {
                    $proxy = $request->server->get('REMOTE_ADDR');
                }
                if ($proxy) {
                    $proxies[] = $proxy;
                }
            }

            Request::setTrustedProxies($proxies, $this->trustedHeaderSet);
        }

        yield $next->handle($request);
    }
}
```

Where the injected ` $trustedProxies` and `$trustedHeaderSet` args should be kernel parameters `kernel.trusted_proxies` and `kernel.trusted_headers`.

If it works for you, I think this middleware could be added to this bundle.

**Comment by digitalkaoz** [comment]
Hey, 

sounds good, doesnt work, maybe i made a mistake, here are my changes:

```yaml
// framework.yml
framework:
  trusted_proxies: '%env(string:TRUSTED_PROXIES)%,REMOTE_ADDR'
  trusted_headers: ['forwarded']
```

```yaml
// baldinof.yml
services:
  Shopware\Production\TrustedProxiesMiddleware:
    arguments:
      $trustedHeaderSet: '%kernel.trusted_headers%'
      $trustedProxies: '%kernel.trusted_proxies%'

baldinof_road_runner:
  middlewares:
    - Shopware\Production\TrustedProxiesMiddleware
```

```php
<?php
namespace Shopware\Production;

use Baldinof\RoadRunnerBundle\Http\MiddlewareInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\HttpKernelInterface;

class TrustedProxiesMiddleware implements MiddlewareInterface
{
	private string $trustedProxies;
	private int $trustedHeaderSet;

	public function __construct(string $trustedProxies, int $trustedHeaderSet)
	{
		$this->trustedHeaderSet = $trustedHeaderSet;
		$this->trustedProxies = $trustedProxies;
	}

	public function process(Request $request, HttpKernelInterface $next): \Iterator
	{
		if (str_contains($this->trustedProxies, 'REMOTE_ADDR')) {
			$proxies = [];
			foreach(explode(',', $this->trustedProxies) as $proxy) {
				$proxy = trim($proxy);
				if ($proxy === 'REMOTE_ADDR') {
					$proxy = $request->server->get('REMOTE_ADDR');
				}
				if ($proxy) {
					$proxies[] = $proxy;
				}
			}

			Request::setTrustedProxies($proxies, $this->trustedHeaderSet);
		}

		yield $next->handle($request);
	}
}
```

```yaml
//.rr.yaml
version: "2.7"

server:
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
  command: "php bin/console baldinof:roadrunner:worker"

http:
  address: "0.0.0.0:8000"
  middleware: [ "static", "gzip" ]
  #pool:
  #  num_workers: 8

  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

logs:
  level: warn
```

(basically following https://symfony.com/doc/current/deployment/proxies.html)

i openend a Ticket at roadrunner itself too (for the FORWARDED header stuff): https://github.com/roadrunner-server/http/pull/9 maybe its needed to work properly (have to wait for a 2.8.1 release)

any hint what might be missing?

The whole application works fine when running with Nginx & FPM.

My Setup is ALB->RR->Symfony

**Comment by Baldinof** [comment]
OK, thanks for trying this out.

I tried a fix here https://github.com/Baldinof/roadrunner-bundle/pull/71 Can you test with the branch from this PR?

**Comment by digitalkaoz** [comment]
still nope...

the app itself requests the following variables (which should be set correctly when the trusted proxies/headers stuff ist set correctly):

```twig
            host: '{{ app.request.host }}',
            port: {{ app.request.port }},
            scheme: '{{ app.request.scheme }}',
            schemeAndHttpHost: '{{ app.request.schemeAndHttpHost }}',
            uri: '{{ app.request.uri }}',
```

**Comment by digitalkaoz** [comment]
i have a feeling we need to wait for a new RR version? from what i can read in your code, it seems correct to me

**Comment by Baldinof** [comment]
I think this should work on the Symfony side: 

I tried with this controller

```php
    #[Route('/test', name: 'test')]
    public function test(Request $request)
    {
        return $this->json([
            'https' => $request->isSecure(),
            'generated_url' => $this->generateUrl('test', referenceType: UrlGeneratorInterface::ABSOLUTE_URL),
            'current_url' => $request->getUri(),
            'real_ip' => $request->getClientIp(),
        ]);
    }
```

With config: 

```yaml
framework:
    trusted_proxies: 'REMOTE_ADDR'
    trusted_headers: ['forwarded']
```

Then running `curl http://localhost:8080/test -H 'Forwarded: for=192.0.2.60;proto=https;by=203.0.113.43;host=example.org'` returns: 

```json
{
   "current_url" : "https://example.org/test",
   "generated_url" : "https://example.org/test",
   "https" : true,
   "real_ip" : "192.0.2.60"
}
```

So it seems OK.

To what I understand from the fix on the RR side, it will make RR hide from the PHP process that it was behind a proxy. The Symfony way of trusting should work as RR is passing the `Forwarded` header.

What is the result of your twig template?
